#!/usr/bin/env bash
###############################################################################
# cov_cli.sh — Print the merged coverage report in the terminal
#
# Usage:  bash cov_cli.sh
#
# Reads sim/cov_report/data/coverage.json (generated by run_uvs.sh's uvcov
# step). Re-run ./run_uvs.sh to refresh it.
###############################################################################
set -euo pipefail
cd "$(dirname "$0")"

JSON=cov_report/data/coverage.json
[ -f "$JSON" ] || { echo "no $JSON — run ./run_uvs.sh first"; exit 1; }

python3 - "$JSON" <<'EOF'
import json, sys

d = json.load(open(sys.argv[1]))

def s(m, k):
    v = m.get(k, {})
    return v.get("score", "-")

print(f"{'module':<22}{'total':>8}{'stmt':>8}{'cond':>8}{'fsm':>8}{'tgl':>8}")
print("-" * 62)
for m in d["modules"]:
    name = m["name"].split("(")[0][:20]
    print(f"{name:<22}{m['total']['score']:>8}{s(m,'stmt'):>8}{s(m,'cond'):>8}{s(m,'fsm'):>8}{s(m,'tgl'):>8}")
EOF
